name: Build and Deploy to Lightsail

on:
  push:
    branches:
      - "*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Debug Secrets
        run: |
          echo "AWS_REGION: $AWS_REGION"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get remove --purge containerd.io containerd
          sudo apt-get update
          sudo apt-get install docker.io
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Set up Lightsailctl extension
        run: |
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl
          export PATH=$PATH:/usr/local/bin/lightsailctl
          lightsailctl --version

      - name: Check version of Docker, AWS CLI and Lightsailctl
        run: |
          docker --version
          aws --version
          lightsailctl --version

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_REGION

      - name: Build and Push Docker Image to Lightsail
        run: |
          docker build --tag layer8-server --file Dockerfile .
          docker images
          make push_layer8_server_image

      - name: Logout from Docker
        run: docker logout
