name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Checkout 
        uses: actions/checkout@v2.3.4

      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with: 
          start: npm run dev